### PR TITLE
Migrate to final location

### PR DESCRIPTION
**Pull request by aschrab**
Check list for doing migration:
- [x] Shutdown services on old pilot
  - [x] apache
  - [x] postfix
  - [x] dovecot
  - [x] mysql
  - [x] cron
  - [x] tribot
- [x] Dump mysql databases
- [x] Do a final merge of `/etc` repos
- [x] Add `AllowUsers` to `/etc/ssh/sshd_config`
- [x] Kick off users
- [x] Clear out or transfer postfix queue contents
- [x] Rsync content
- [x] Merge this and run the `migrate` playbook
- [x] Merge `migrate` branch of `/etc` repo on pilot VM (available on old pilot as well)
- [x] Restore mysql databases

### CODE REVIEW

**Comment by Jmainguy** [comment]
Looking at the 4 files this adds / changes, this looks good to me.

**Comment by Jmainguy** [comment]
Regarding the checklist for the migration

do a mysqldump of all mysql databases before disabling mysql service
include tribot as a service to dsiable

I am assuming /home is included in "rsync content"
add a import mysql databases on new pilot before saying all clear.

**Comment by briangerard** [comment]
It all looks good to me too.  Nicely done!

**Comment by scottlinux** [comment]
+1 !!!!!!!

**Pull request merged**
